### PR TITLE
Update esp-web-tools

### PR DESCRIPTION
**Pull request by lorenzodellagiustina**
Esp32-c3: old version throwing an error. Solved updating esp-web-tools.

Working artifacts at https://github.com/lorenzodellagiustina/esp-web-flash-server/releases/latest/download/web-flash-${ARCH}.zip

### CODE REVIEW

**Comment by bjoernQ** [comment]
Works for me with and without this fix

Maybe not pinning the version of esp-web-tools and just using latest is a good thing as long as it won't use a future newer version which is incompatible
@SergioGasquez what do you think?

**Comment by lorenzodellagiustina** [comment]
Yea, maybe it is better to pin it at the current newer version.

Without the update throws this error to me:
Screenshot 2024-01-22 090808

**Comment by bjoernQ** [comment]
Interesting - probably pinning the version to the current `9.4.3` would be the best solution

**Comment by SergioGasquez** [comment]
I would also go for using the latest version release (pinned) to avoid it from breaking due to new versions in the future.

**Review by SergioGasquez — APPROVED** [review]
LGTM!

**Review by bjoernQ — APPROVED** [review]
LGTM - Thanks!

**Pull request merged**
