### PR TITLE
Pin espflash dependency to commit hash

### LINKED ISSUE #3: Dependency not found
Hi there,
just tried to to execute install-rust-toolchain.sh and found out that a dep. on your package is breaking the build - output below:

```
$ Installing web-flash v0.1.0 (https://github.com/bjoernQ/esp-web-flash-server#946047a5)
$   Updating crates.io index
$   Updating git repository `https://github.com/esp-rs/espflash`
$ error: failed to compile `web-flash v0.1.0 (https://github.com/bjoernQ/esp-web-flash-server#946047a5)`, intermediate artifacts can be found at `/tmp/cargo-installBPdfpO`
$ Caused by:
$ failed to get `espflash` as a dependency of package `web-flash v0.1.0 (/home/esp/.cargo/git/checkouts/esp-web-flash-server-033e701f302416a2/946047a)`
$ Caused by:
$   failed to load source for dependency `espflash`
$ Caused by:
$   Unable to update https://github.com/esp-rs/espflash?branch=bugfix/chip-name-esptool
$ Caused by:
$   failed to find branch "bugfix/chip-name-esptool"
```

Looks like the branch "bugfix/chip-name-esptool" is gone for "espflash". If you can explain what was the purpose of using a bugfix branch as a dep, I can create a PR.

### PR DESCRIPTION
**Pull request by bjoernQ**
@thefill this should fix #3 - would be great if you can verify this - Thanks

### CODE REVIEW

**Comment by thefill** [comment]
I can confirm this fixes the issue. 

Question: wouldn't it be better to create a fork of their package based on rev "55bce336c6718c1c7f019e4da718f97c8cdf1b95" just in case they try to prune the repo?

**Comment by thefill** [comment]
* just to clarify: and then you could refer to this in deps ^^

**Comment by bjoernQ** [comment]
Thanks! This is just meant as a quick-fix. My plan is to depend on a version published on crates.io but I just wanted to get this back into a working state as soon as possible

Again, thanks for reporting and your support

**Comment by thefill** [comment]
> Thanks! This is just meant as a quick-fix. My plan is to depend on a version published on crates.io but I just wanted to get this back into a working state as soon as possible
> 
> Again, thanks for reporting and your support

Got it - yep def a lot better UX when exploring deps. No probs, glad I could help & thanks for a quick reply!

**Comment by thefill** [comment]
@bjoernQ quick question: planning to make new release with this change? Would love to test this with install-rust-toolchain.sh

**Comment by bjoernQ** [comment]
Sure - the builds are done now

**Comment by thefill** [comment]
> Sure - the builds are done now

Ok checked - all is peachy now <3

**Pull request merged**
